### ISSUE TITLE
Главное меню: при переходе в пункты Проекты и Задачи появляется сообщение "Ошибка сервера"

### ISSUE THREAD

**Issue by MangolSergey** [vliplianina/practice-tasks#19]
Окружение:

- Модель устройства: Redmi 3S
- Версия ОС: Android 6.0.1 MMB29M

Баг воспроизведен:

1) Модель устройства: Xiaomi Redmi 6
Версия ОС: Android 8.1.0 O11019

2) Модель устройства: Meizu 16th
Версия ОС: Android 8.1.0

3) Модель устройства: Xiaomi Mi A
Версия ОС: Android 9 pie

Шаги воспроизведения:
1) Перейти в пункт Проекты или Задачи в главном меню

Ожидаемый результат:
- Переход на экран Список проектов/Список задач и загрузка данных

Фактический результат:
- Переход на экран и появление сообщения "Ошибка сервера". Данные на экранах не загружены

**Comment by kozant** [comment]
Баг воспроизведён:

- Модель устройства: Xiaomi Redmi 6
- Версия ОС: Android 8.1.0 O11019

**Comment by henry-monstein** [comment]
Баг воспроизведен

- Os: Android 9 pie
- Xiaomi mi a2

**Comment by Janekushar** [comment]
Баг воспроизведен

Os: Android 8.1
Meizu 16th

**Comment by MangolSergey** [comment]
Баг исправлен в билде v24072019
