### ISSUE TITLE
Главное меню: при нажатии нажатии на "Сотрудники" пересылает на главный экран

### ISSUE THREAD

**Issue by henry-monstein** [vliplianina/practice-tasks#20]
Окружение:

- Xiaomi Mi A2
- Android 9 pie

Шаги воспроизведения:

- В главном меню выбрать "Сотрудники"

Ожидание: 

- Переходит во вкладку сотрудники

Результат:

- Переходит обратно на главный экран

Комментарий:

- Баг устранен на версии 24072019

**Comment by kozant** [comment]
Баг не воспроизведён: 

- Модель устройства: Redmi 6
- Версия ОС: Android 8.1.0 O11019

**Comment by Janekushar** [comment]
Баг воспроизведён:

Модель устройства: Meizu 16th
Версия ОС: Android 8.1.0

**Comment by MangolSergey** [comment]
Баг воспроизведен:
- Модель устройства: Redmi 3S
- Версия ОС: Android 6.0.1 MMB29M
