### ISSUE TITLE
Главное меню: Крэш при нажатии на кнопку "Сотрудники"

### ISSUE THREAD

**Issue by kozant** [vliplianina/practice-tasks#21]
**Окружение:** 
Xiaomi Redmi 6 Android 8.1.0 
Redmi 3S Android 6.0.1 
Xiaomi Mi A2 Android 9 (Воспроизводится нестабильно)
  
**Шаги воспроизведения:**

1. Открыть приложение
2. Нажать на кнопку "Сотрудники"

**Ожидаемый результат:**
Переход на выбранную страницу и загрузка данных на ней.

**Фактический результат:**
Крэш.

**Comment by Janekushar** [comment]
Баг не воспроизведён:

Модель устройства: Meizu 16th
Версия ОС: Android 8.1.0

**Comment by MangolSergey** [comment]
Баг воспроизведен:
- Модель устройства: Redmi 3S
- Версия ОС: Android 6.0.1 MMB29M

**Comment by henry-monstein** [comment]
Баг воспроизводится после второго нажатия на "Сотрудники"

- Xiaomi Mi A
- Android 9 pie

**Comment by kozant** [comment]
**Окружение:**
Redmi 6 Android 8.1.0

**Исправлено в версии:**
24072019
