### ISSUE TITLE
Главное меню: при нажатии на задачи происходят ошибки

### ISSUE THREAD

**Issue by henry-monstein** [vliplianina/practice-tasks#22]
Окружение:

- Xiaomi Mi A2
- Android 9 pie

Шаги воспроизведения:

- Выбираем кнопку "Задачи".

Ожидание: 

- Загрузка имеющихся заданий.

Результат:

- Вызывается "ошибка сервера" и "ошибка загрузки заданий"

Комментарий: 

- Баг устранен на версии 24072019

**Comment by Janekushar** [comment]
Баг воспроизведён:

Модель устройства: Meizu 16th
Версия ОС: Android 8.1.0

**Comment by MangolSergey** [comment]
Баг воспроизведён:
Модель устройства: Redmi 3S
Версия ОС: Android 6.0.1 MMB29M

**Comment by kozant** [comment]
Баг воспроизведён:

- Модель устройства: Redmi 6
- Версия ОС: Android 8.1.0 O11019
