### ISSUE TITLE
Форма ввода проекта: Крэш при попытке сохранить введённые данные в поля "Наименование проекта" и "Описание проекта"

### ISSUE THREAD

**Issue by kozant** [vliplianina/practice-tasks#23]
**Окружение:**
Xiaomi Redmi 6 Android 8.1.0 
Meizu 16th Android 8.1.0 (воспроизводится не стабильно)
Xiaomi Mi A2 Android 9  
Redmi 3S Android 6.0.1

**Шаги воспроизведения:**
1. В главном меню, нажать на кнопку "Проекты".
2. Нажать на иконку "Добавить"
3. Ввести данные в поля "Наименование проекта" и "Описание проекта".
4. Нажать кнопку "Сохранить".

**Ожидаемый результат:** 
Сохранение записи, переход к форме со списком проектов.

**Фактический результат:**
Крэш.

**Comment by Janekushar** [comment]
Баг  не воспроизведён:

- Модель устройства: Meizu 16th
- Версия ОС: Android 8.1.0

**Comment by MangolSergey** [comment]
Баг воспроизведен:
- Модель устройства: Redmi 3S
- Версия ОС: Android 6.0.1 MMB29M

**Comment by henry-monstein** [comment]
Баг воспроизводится не каждый раз

- Xiaomi Mi A2
- Android 9 pie

**Comment by kozant** [comment]
**Окружение:**
Redmi 6 Android 8.1.0

**Исправлено в версии:**
24072019
