### ISSUE TITLE
Форма ввода проекта: при попытке сохранить данные выкидывает на главный экран

### ISSUE THREAD

**Issue by Janekushar** [vliplianina/practice-tasks#24]
Окружение:

- Meizu 16th
- Android 8.1 Oreo

Шаги воспроизведения:

- Заполнить поля нужными данными.
- Нажать кнопку сохранить.

Ожидание:

- Данные сохранены.

Результат:

- Данные не сохранены и пересылает на главный экран.

Комментарий:

- Баг воспроизводиться не каждый раз.

Комментарий:

- Баг устранен на версии 24072019

**Comment by MangolSergey** [comment]
Баг воспроизведен:
- Модель устройства: Xiaomi Redmi 6
- Версия ОС: Android 8.1.0 O11019

Комментарий: из 5 попыток все 5 переходов на главный экран

**Comment by kozant** [comment]
Баг не воспроизведён:

- Модель устройства: Redmi 6
- Версия ОС: Android 8.1.0 O11019

**Comment by henry-monstein** [comment]
Баг воспроизведен (воспроизводится не каждый раз):

- Xiaomi Mi A2
- Android 9 pie
