### ISSUE TITLE
Форма ввода проекта: данные не сохраняются 

### ISSUE THREAD

**Issue by henry-monstein** [vliplianina/practice-tasks#26]
Окружение: 

- Xiaomi Mi A2
- Andriod 9 pie

Шаги воспроизведения:

- Заполнить поля нужными данными.
- Нажать кнопку сохранить.

Ожидание:

- Данные сохранены.

Результат:

- Данные не сохранены и вызывается "ошибка сервера" 

Комментарий:

Баг воспроизводиться не каждый раз.

**Comment by kozant** [comment]
Баг не воспроизведён:

- Модель устройства: Redmi 6
- Версия ОС: Android 8.1.0 O11019

**Comment by MangolSergey** [comment]
Баг не воспроизведён:
- Модель устройства: Redmi 3S
- Версия ОС: Android 6.0.1 MMB29M
