### ISSUE TITLE
Список проектов/Список задач: не реагирует на тап кнопка "обновить"

### ISSUE THREAD

**Issue by MangolSergey** [vliplianina/practice-tasks#27]
Окружение:
- Модель устройства: Redmi 3S
- Версия ОС: Android 6.0.1 MMB29M

Баг воспроизведен:
1) Модель устройства: Redmi 6
Версия ОС: Android 8.1.0 O11019

Шаги воспроизведения:
1) переходим в Список проектов
2) тапаем на кнопку обновить
3) переходим в главное меню и тапаем на Список задач
4) тапаем на кнопку обновить

Ожидаемый результат:
- обновление страниц после этапов 2 и 4 

Фактический результат:
- ничего не происходит

**Comment by kozant** [comment]
Баг воспроизведён:

- Модель устройства: Redmi 6
- Версия ОС: Android 8.1.0 O11019

**Comment by MangolSergey** [comment]
Баг исправлен в билде v24072019
Окружение:
- Модель устройства: Redmi 3S
- Версия ОС: Android 6.0.1 MMB29M
