### ISSUE TITLE
Форма ввода данных: добавить валидацию на ввод данный, так как в качестве данных можно указать " " (пробел)

### ISSUE THREAD

**Issue by henry-monstein** [vliplianina/practice-tasks#34]
**Окружение:**
Model: Xiaomi Mi A2; OS: Android 9 Pie

**Шаги воспроизведения:**

1. Заполнить текстовые поля ввода пробелом (актуально для полей "Наименование" и "Описание" в форме создания проекта, "Наименование" в форме создания задачи, "Фамилия", "Имя", "Отчество" и "Должность" в форме создания сотрудника).
2. Остальные поля заполняем корректными данными. 

**Ожидаемый результат:**
Сообщение об ошибке ввода

**Полученный результат:** 
Данные сохраняются

**Комментарий:**
Существует необходимость для подобного ввода

**Comment by kozant** [comment]
Баг воспроизведён:
1. Модель устройства: Redmi 6
2. Версия ОС: Android 8.1.0 O11019

**Comment by MangolSergey** [comment]
Баг воспроизведен:
- Модель устройства: Redmi 3S
- Версия ОС: Android 6.0.1 MMB29M
