### ISSUE TITLE
Форма ввода задачи: сделать невозможным указать в поле "Работа" 0 часов

### ISSUE THREAD

**Issue by henry-monstein** [vliplianina/practice-tasks#35]
**Окружение:**
Model: Xiaomi Mi A2; OS: Android 9 Pie

**Шаги воспроизведения:**

1. В форме создания задачи указать в качестве работы 0 часов
2. Заполнить остальные поля валидными данными

**Ожидаемый результат:** 
Сообщения о недопустимости введенных данных

**Полученный результат:** 
Данные сохранены 

**Комментарий:**
Оправдано существовании работы 0 часов, для задач, которые требуют меньше часа на выполнение

**Comment by kozant** [comment]
Баг воспроизведён:

Модель устройства: Redmi 6
Версия ОС: Android 8.1.0 O11019

**Comment by MangolSergey** [comment]
Баг воспроизведен
- Модель устройства: Redmi 3S
- Версия ОС: Android 6.0.1 MMB29M
