### ISSUE TITLE
Список проектов/задач/сотрудников: При появлении скролла в форме, записи начинают повторяться

### ISSUE THREAD

**Issue by kozant** [vliplianina/practice-tasks#40]
**Окружение:**
- Модель устройства: Redmi 6
- Версия ОС: Android 8.1.0 O11019

Актуально для списка проектов/задач/сотрудников:

**Предусловие:**

1. Изменить в настройках значение отображения записей с текущего на 13 и более или на 0 для отображения всех записей.
2. Перейти в форму "Список проектов".
3. Создать минимум 13 записей.

**Шаги воспроизведения на примере формы со списком проектов:**

1. Перейти в форму "Список проектов".

**Ожидаемый результат:**
Все отображаемые записи имеют названия и описания, указанные в создании этих записей.

**Фактический результат:**
Записи, отображаемые после появления скролла, начинают повторяться, начиная с начала.

**Comment by henry-monstein** [comment]
**Баг исправлен в билде v27072019**

**Окружение:**
Модель устройства: Xiaomi Mi A2
Версия ОС: Android 9.0 Pie
