### ISSUE TITLE
Список Проектов/Задач/Сотрудников: при резком скролле страницы сбиваются записи Проектов/Задач/Сотрудников соответственно

### ISSUE THREAD

**Issue by henry-monstein** [vliplianina/practice-tasks#41]
**Окружение:**
Model: Xiaomi Mi A2; OS: Andriod 9 Pie

**Предусловие:**

1. Изменить в настройках количество отображаемый записей на странице (к примеру 99 записей, но минимум 13)
2. Заполнить страницу достаточным количеством записей.

**Шаги воспроизведения:**

1. Резко проскроллить список Проектов/Задач/Сотрудников.

**Полученный результат:**
Записи Проектов/Задач/Сотрудников в списке путаются (отображаемая запись не соответствует внутренней информации)

**Ожидаемый результат:**
Происходит правильный скролл.

**Комментарий:**
Записи меняются попарно, то есть каждый резкий скролл создает пару, которая меняется записями в списке. Все возвращается к норме при обновлении страницы. Так же коррелирует с https://github.com/vliplianina/practice-tasks/issues/40  

**Комментарий 2:** 
Исправлено на версии v27072019

![ezgif-4-eb7869916115](https://user-images.githubusercontent.com/23211292/61951296-4c92a400-afb9-11e9-8e32-0d6cd8865bcb.gif)

![ezgif-4-70b91b270ed1](https://user-images.githubusercontent.com/23211292/61951361-764bcb00-afb9-11e9-9fba-11047d8e28c3.gif)

**Comment by kozant** [comment]
Баг воспроизведён:
- Модель устройства: Redmi 6
- Версия ОС: Android 8.1.0 O11019
